name: Despliegue a Produccion

on:
    push:
        branches:
            - master # Se ejecutará cada vez que subas código a master

jobs:
    deploy:
        name: Desplegar la app
        runs-on: ubuntu-latest
        # ESTA ES LA LÍNEA MÁGICA: Le dice a GitHub y a Jira que esto es un despliegue
        environment: Production

        steps:
            - name: Descargar el código
              uses: actions/checkout@v4

            - name: Simulando el proceso de despliegue...
              run: |
                  echo "Iniciando el despliegue para el ticket asociado..."
                  sleep 5
                  echo "¡Despliegue completado con éxito!"
